[package]
name = "chigui-core"
version = "0.0.0"
edition = "2024"
rust-version = "1.86.0"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
